### ISSUE TITLE
框架是假的人的能力也是假

### ISSUE THREAD

**Issue by teaxus** [HeroOnline/HCTabBarKit#2]
框架是假的人的能力也是假

**Comment by coffee-developer** [comment]
这个人菜的一笔,我前公司技术总监,我对他各种无语,他拿着一本书在制定公司框架,那个框架把我们坑惨了,给我们加了很多副作用,更可笑的是复制开源框架的代码,改个类名就提交说是他写的;来公司也没事做拿手机拍我们玩手机,拍到就约谈赶人走

**Comment by coffee-developer** [comment]
天天下午四五点来公司上班,到了凌晨发朋友给老板看,假装奋斗逼,恶心
